spring:
  datasource:
    url: jdbc:mysql://database-1.cxhez1bhipyf.us-east-2.rds.amazonaws.com:3306/foodcourt
    username: admin
    password: admin123

  application:
    name: foodcourtusers


  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000